spring:
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:cursos
    username: sa
    password:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    properties:
      hibernate:
        show_sql: true
        format_sql: true
  cache:
    type: redis
  redis:
    host: localhost
    port: 6379
  mail:
    host: sandbox.smtp.mailtrap.io
    port: 2525
    username: 875ecd66a05aac
    password: 3081f2a111f399
    properties:
      mail:
        transport:
          protocol: smtp
        debug: true
        smtp:
          auth: true
          starttls:
            enable: true
thymeleaf:
  mode: HTML
jwt:
  secret: secreto
